apiVersion: v1
kind: ConfigMap
metadata:
  name: fileshare-config
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "fileshare_db"
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_BUCKET_NAME: "fileshare-storage"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
