apiVersion: v1
kind: Secret
metadata:
  name: fileshare-secrets
type: Opaque
stringData:
  POSTGRES_USER: "fileshare_user"
  POSTGRES_PASSWORD: "fileshare_pass"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
